---
output: 
  bookdown::pdf_document2:
    keep_tex: true
    toc: false
---

## Data and Model of Interest

### Data

Data collected by the National Alzheimer's Coordinating Center (NACC) Uniform Data Set Version 2.0 (UDS, September 2014) was used to test the proposed MLLT model validity. Criteria for entry into the analysis requires Alzheimer's disease participants to have transitioned from cognitively normal to mild cognitive impairment (MCI) or Dementia during the NACC follow-up period. For the multivariate modelling of different cognition domains, we used the following neuropsychological outcomes: logic memory, memory units, digit forward, digit backward, trails A, trails B, WAIS, boston naming, animals naming, and vegetables naming. Predictors of interest include: time, race white, sex, apoe e4 status, education, time of transition from cognitively normal to mild cognitive impairment (MCI) or dementia, and age.


Inclusion into the analysis requires non-missingness for covariates and each test at a given time point, as well as each participant nedding 1 or more complete observation. This results in 738 participants with an average of 5.13 return visits (SD = 2.06) seen over a period of 5.01 years (SD = 2.17). The average transition from cognitively normal to MCI or Dementia occurs after 3.82 years (SD = 1.88). In this sample 37.3% of the subjects carry at least 1 APOE e4 allele. The average study participants are predominantly female (61.5%) and of white ethnicity (86.2%). Participants are primarily older with an average age of 78.2 years old (SD = 7.60) and have an average of 15.9 years of education (SD = 6.09).

### Model of Interest


After controlling for dementia status (1 = diagnosed with MCI or dementia, 0 = otherwise), sex (1 = female, 0 = male), race (1 = white, 0 = other), age (mean centered), and education (mean centered), we wish to accurately estimate the effect of having an APOE e4 allele (1 = has at least 1 APOE e4 allele, 0 = otherwise) on each test trajectory. Previous research suggests that the effect of APOE e4 status differs between males and females, therefore an interaction between e4 status and sex is included in the model. To measure the effect of the dependent variables on the cognition tests trajectory, all dependent variables are put into the model as an interaction with time. To assure particpants are in a similar progression of AD, we also include a linear spline for when the participant transitions from cognitively normal to MCI or dementia.