---
output: 
  bookdown::pdf_document2:
    keep_tex: true
    toc: false
---

## Discussion

The multivariate local linear trend state space model was developed to assess inter-relationships between cognitive tests spanning different cognition domains. It achieves this by modeling the correlation between tests in both the observation equation and the underlying cognition process equation, after accounting for linear effects. By controlling for linear effects we are able to control for possible cohort difference when estimating the inter-relatedness.

The fully simulated data simulation shows the MLLT where, correlation is assumed in the observation and state equations, is the most robust model for the varying correlation assumptions. This MLLT was able to accurately estimate the inter-relatedness of the simulated cognitive tests in both the observation and state equations. In addition, the MLLT also as proficient as the LLT in estimating linear effects on the outcome.

The real data simulation provided insight into how the MLLT performs on real data provided by the NACC. The OS and S MLLT models were able to accurately estimate the added linear effect on the real outcomes and were as accurate as the proven LLT model. The O MLLT suffered in terms of proper 95% confidence interval coverage. Reasoning was made apparent by the correlation structure estimated by the OS model, which put very low covariance in the observation equation and high covariance in the state equation. These results help confirm the true underlying data generation process is more likely that of an S or OS model. The findings also support the importance in estimating the underlying cognition process unaccounted for by the linear effects of interest.

Similar to the LLT, the dynamic MLLT is able to  estimate linear effects of interest well, but, unlike the LLT, the MLLT can also provide accurate inference of linear effects across different cognitive outcomes. To test if an independent variable has a significantly different effect between tests, we rely on outcome standardization, which relies on accurate estimation of the observation error correlation matrix. Pre-standardizing the data is ineffective as, according to our model, variation in the outcome can come from the measurement error or from the latent cognition process. For this reason we propose standardizing the outcome during each step of the Bayesian Gibb's sampler.

Depending on statistical power and the objectives of an analysis, different assumptions of the underlying model can be assumed. First, it can be assumed that correlation in the observations exists only in the observation errors. This assumption can be made when linear effects and cross test linear effect comparisons are of primary interest. Next, it can be assumed that the correlation exists only in the underlying latent cognition process. This can be used when the primary focus of the analysis is understanding latent constructs of cognition. However, for an ample sample size we can assume that there is correlation in the observation error and in the latent cognition process. This is the proffered model and provides the most accurate results regardless of analysis aims.
