---
title: "Untitled"
output: html_document
---

```{r}
library(mvtnorm)
library(tidyverse)
source("functions/ffbsJoint.R")
```



```{r}
# set.seed(123)
numits <- 2000
cs <- 2
n <- 100
sigeps <- c(25, 5, 5, 20)

SIGeps <- matrix(sigeps, 2, 2)

Sigma <- matrix(c(10, 0, 0, 10), 2)

TT <- 10

B1 <- c(4, 2, 1)
B2 <- c(-3, 0, 1)

B <- cbind(B1, B2)

etas <- rmvnorm(TT * n, sigma = Sigma)
epss <- rmvnorm(TT * n, sigma = SIGeps)

mydatraw <- data.frame(
  id = sort(rep(1:n, TT)),
  time = 1:TT,
  eta1 = etas[,1],
  eta2 = etas[,2],
  eps1 = epss[,1],
  eps2 = epss[,2]
) %>%
  group_by(id) %>%
  mutate(

    alpha1 = cumsum(eta1), 
    alpha2 = cumsum(eta2),
    x1 = time,
    x2 = rbinom(1, 1, .5) * time,
    oind = c(sample(c(TRUE, rep(FALSE, TT-2))), FALSE),
    oind = any(oind) & time >= time[oind],
    oind = time*oind,
    x3 = ifelse(oind > 0, time - min(oind[oind> 0]), 0),
    Kern1 = B1[1] * x1 + B1[2] * x2 + B1[3] * x3,
    Kern2 = B2[1] * x1 + B2[2] * x2 + B2[3] * x3,
    # Kern1 = B1[1] * x1,
    # Kern2 = B2[1] * x1,
    y1 = alpha1  + Kern1 + eps1,
    y2 = alpha2  + Kern2 + eps2,
    # Keep = TRUE
    Keep = c(TRUE, sample(c(TRUE, FALSE), TT - 2, replace = TRUE), TRUE)
  ) 

mydat <- mydatraw %>% 
  filter(Keep) %>%
  mutate(timeDiff = c(diff(time), NA))%>%
  ungroup()

nrow(mydat)
```

```{r}
ndat <- mydat %>%
  group_by(id) %>%
  nest() %>%
  .[["data"]] 

y <- ndat %>%
  map(~select(.x, y1, y2)) %>%
  map(~t(as.matrix(.x)))


X <- ndat %>%
  # map(~select(.x, x1, x2, x3)) %>%
  map(~select(.x, starts_with("x"))) %>%
  map(~(as.matrix(.x)))

time <- ndat %>%
  map("time")

timeDiff <- ndat %>%
  map("timeDiff") %>%
  map(~.x[!is.na(.x)])



 
Neta <- (map_dbl(timeDiff, length) %>% sum())
Ntotal <-  nrow(mydat)

W = Sigma
# W = diag(c(30, 30), cs)
V = SIGeps
# V = diag(c(15, 15), cs)
# timeDiff = 1
m0 <- 0 
C0 <- diag(1, cs)
###Need another way to set "TT", not ncol (y)
a0 <- 0.01
b0 <- 0.01
c0 <- 0.01
d0 <- 0.01
prior.nu.eta <- 0.01
###
# Beta.Initial <- numeric(length(B))
# Beta.Initial <- B # matrix(0, nrow(B), ncol(B))
B1.initial <- lm(y1 ~ x1 + x2 + x3 , data = mydat)$coef[-1]
B2.initial <- lm(y2 ~ x1 + x2 + x3 , data = mydat)$coef[-1]


sigma2.beta <- 10

B.star <- cbind(B1.initial, B2.initial)

Beta.Initial <- numeric(length(B.star))


B2 <- matrix(B.star, ncol = cs)

XtX <- mydat %>%
  select(starts_with("x")) %>%
  as.matrix() %>%
  crossprod()

sig2beta_XtX <- sigma2.beta * XtX

CPbig <- lapply(1:n, function(i){
  lapply(1:nrow(X[[i]]), function(x)outer(X[[i]][x,],X[[i]][x,])) %>%
    Reduce("+", .)
}) %>%
    Reduce("+", .)
    


ex <- eigen(sig2beta_XtX, symm = TRUE)



# Tracking obj
Beta.Track <- array(NA, dim = c(ncol(X[[1]]), cs, numits))
vcovWish <- wcovWish <- array(NA, dim = c(cs, cs, numits))
sigma2.eps.Track <- matrix(NA, nrow = numits, ncol = cs)


prior.nu.eta <- cs + 1
prior.Gamma.eta <- diag(1, cs)

It <- 0
it <- It+1

```




```{r}
for(It in 1:numits){
    
    
    i <- 1
    y.star <- lapply(1:n, function(i){
      y[[i]]-t(X[[i]] %*% B.star)
    })
    
    
    
    ####### alpha
    bout <- lapply(1:n, function(i){
      ffbs.joint(y = y.star[[i]], V = V,W = W,m0 = m0,C0 = C0, timeDiff = timeDiff[[i]])$x
    })
    
    
    
    ####### Sigma eta
    fp <- lapply(1:n, function(i){
      apply(bout[[i]], 1, function(z)diff(z)^2) / timeDiff[[i]]
      
    }) %>%
      do.call("rbind", .) %>%
      colSums()
    
    W <- diag(sapply(fp, function(x){
      1/rgamma(1, (Neta/ 2 + a0), (b0 + x/ 2))
    }))
    
    wcovWish[,,It] <- W
    
    ###### Sigma eps
    
    or <- lapply(1:n, function(i){
      ((y.star[[i]] - bout[[i]]))
    })  %>%
      do.call("cbind", .) %>%
      tcrossprod()
    
    
    V <- vcovWish[,,It] <- cIRT::riwishart(prior.nu.eta + Ntotal, or + prior.Gamma.eta)
    

    
    # #### Beta Post
    
    SIGepsInv <- solve(V)
    daSig <- kronecker(SIGepsInv, CPbig)
    diag(daSig) <- diag(daSig) + 1/sigma2.beta
    
    daSiginv <- solve(daSig)
    
    daB <- lapply(1:n, function(i){
      yas <- crossprod(y[[i]] - bout[[i]], SIGepsInv)
      lapply(1:ncol(yas), function(x)yas[,x]*X[[i]]) %>%
        do.call("cbind", .)
    })  %>%
        do.call("rbind", .) %>%
      colSums()
    

    BetaSim <- rmvnorm(1, daB %*% daSiginv, sigma = daSiginv)


    B.star <- Beta.Track[,,It] <- matrix(BetaSim, ncol = cs)
  }
```



```{r}
BayesKalmJointOutcomeCor(mydat, c("y1", "y2"), c("x1", "x2", "x3"), "time", "id", numits = 50, silence = FALSE, seed = NULL, numitInit = 100, burnInit = 50  )
```


```{r}
thin <- 1
# burn <- numits/2 + 1
burn <- 1000
burnp <- burn/thin 

# apply(vcovWish, 1:2, mean)
# Sigma
# 
# Sigma > apply(vcovWish[,,seq(1, numits, thin)], 1:2, quantile, .025) & Sigma < apply(vcovWish[,,seq(1, numits, thin)], 1:2, quantile, .975)


##SIGETA

CI <- quantile(wcovWish[1,1,seq(burn, numits, thin)], c(.025, .975))
Covered <- CI[1] < Sigma[1,1] & CI[2] > Sigma[1,1]
plot(wcovWish[1,1,seq(1, numits, thin)], main = paste("ETA11 Covered: ", Covered))
abline(h = CI[1], col = "green")
abline(h = CI[2], col = "green")
abline(h = Sigma[1,1], col = "red")
abline(v = burnp, lty = 2)


CI <- quantile(wcovWish[1,2,seq(burn, numits, thin)], c(.025, .975))
Covered <- CI[1] < Sigma[1,2] & CI[2] > Sigma[1,2]
plot(wcovWish[1,2,seq(1, numits, thin)], main = paste("ETA21 Covered: ", Covered))
abline(h = CI[1], col = "green")
abline(h = CI[2], col = "green")
abline(h = Sigma[1,2], col = "red")
abline(v = burnp, lty = 2)


CI <- quantile(wcovWish[2,2,seq(burn, numits, thin)], c(.025, .975))
Covered <- CI[1] < Sigma[2,2] & CI[2] > Sigma[2,2]
plot(wcovWish[2,2,seq(1, numits, thin)], main = paste("ETA22 Covered: ", Covered))
abline(h = CI[1], col = "green")
abline(h = CI[2], col = "green")
abline(h = Sigma[2,2], col = "red")
abline(v = burnp, lty = 2)



##SIGEPS

CI <- quantile(vcovWish[1,1,seq(burn, numits, thin)], c(.025, .975))
Covered <- CI[1] < SIGeps[1,1] & CI[2] > SIGeps[1,1]
plot(vcovWish[1,1,seq(1, numits, thin)], main = paste("EPS11 Covered: ", Covered))
abline(h = CI[1], col = "green")
abline(h = CI[2], col = "green")
abline(h = SIGeps[1,1], col = "red")
abline(v = burnp, lty = 2)


CI <- quantile(vcovWish[1,2,seq(burn, numits, thin)], c(.025, .975))
Covered <- CI[1] < SIGeps[1,2] & CI[2] > SIGeps[1,2]
plot(vcovWish[1,2,seq(1, numits, thin)], main = paste("EPS21 Covered: ", Covered))
abline(h = CI[1], col = "green")
abline(h = CI[2], col = "green")
abline(h = SIGeps[1,2], col = "red")
abline(v = burnp, lty = 2)


CI <- quantile(vcovWish[2,2,seq(burn, numits, thin)], c(.025, .975))
Covered <- CI[1] < SIGeps[2,2] & CI[2] > SIGeps[2,2]
plot(vcovWish[2,2,seq(1, numits, thin)], main = paste("EPS22 Covered: ", Covered))
abline(h = CI[1], col = "green")
abline(h = CI[2], col = "green")
abline(h = SIGeps[2,2], col = "red")
abline(v = burnp, lty = 2)

##BETA

betadf <- map(1:numits, function(i){
  bdf <- Beta.Track[,,i] %>%
    as.data.frame()
  colnames(bdf) <- paste("C", 1:ncol(bdf), sep = "")
  row.names(bdf) <- paste("B", 1:nrow(bdf), sep = "")
  
  bdf %>% 
    rownames_to_column("Beta") %>%
    gather("outcome", "value", starts_with("C")) %>%
    mutate(Param = paste(Beta, outcome, sep = ""), iteration = i)
}) %>%
  do.call("rbind", .)

betadf %>%
  group_by(Param) %>%
  nest() %>%
  mutate(plots = map2(data, Param,function(df, title){
    
    df <- filter(df, iteration %in% seq(1, numits, thin))
    
    i <- substr(df$Beta[1], 2, nchar(df$Beta[1])) %>% as.numeric()
    j <- substr(df$outcome[1], 2, nchar(df$outcome[1])) %>% as.numeric()
    
    CI <- quantile(df$value[df$iteration >= burn], c(0.025, 0.975))
    B.mean <- mean(df$value[df$iteration >= burn])
    Covered <- CI[1] < B[i,j] & CI[2] > B[i,j]
    
    df %>%
      ggplot(aes(x = iteration, y = value)) + 
      geom_point() +
      geom_hline(yintercept = B[i,j], color = "red") +
      geom_hline(aes(yintercept = B.mean),color = "blue") +
      geom_hline(aes(yintercept = CI[1]),color = "green") +
      geom_hline(aes(yintercept = CI[2]),color = "green") +
      geom_vline(aes(xintercept = burnp), linetype = 2) +

      ggtitle(paste(title, "Covered:", Covered))
  })) %>%
  .[["plots"]]


```



