---
title: Multivariate State Space Models for Neuropsychological Cognitive Scores
output: 
  bookdown::pdf_document2:
    keep_tex: true
    classoption: 12pt
author:
  - Zach Baucom, BS, zhbaucom@bu.edu
  - Yorghos Tripodis, PhD, yorghos@bu.edu
  - Michael Alosco, PhD, malsoco@bu.edu
  - Evan Johnson, PhD, wej@bu.edu
abstract: ""
bibliography: bibliography.bib
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{amsmath}
- \usepackage{algorithm,algorithmic}
- \addtolength{\oddsidemargin}{-.5in}%
- \addtolength{\evensidemargin}{-.5in}%
- \addtolength{\textwidth}{1in}%
- \addtolength{\textheight}{-.3in}%
- \addtolength{\topmargin}{-.8in}%
- \usepackage{float}
- \floatplacement{figure}{H}
---

\newpage{}

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r child = "Paper2/Introduction.Rmd", cache = FALSE, eval = TRUE}

```

# Methods

```{r child = "Paper2/DataModel.Rmd", cache = FALSE, eval = TRUE}

```

```{r child = "Paper2/Methods.Rmd", cache = FALSE, eval = TRUE}

```


# Model Validation


```{r child = "Paper2/FullSimulation.Rmd", cache = FALSE, eval = TRUE}


```


```{r child = "Paper2/RealDataSim.Rmd", cache = FALSE, eval = TRUE}

```




```{r child = "Paper2/DataAnalysis.Rmd", cache = FALSE, eval = TRUE}

```


```{r child = "Paper2/Discussion.Rmd", cache = FALSE, eval = TRUE}

```

\newpage{}

# Bibliography
